
  const i18n = {
    en: {
      site_title: 'Free Online Tools',
      site_desc: '12 free tools · No signup · No ads on tools · Works offline after first load',
      cat1_title: 'Developer Tools',
      cat1_count: '7 tools',
      cat2_title: 'Design & Color',
      cat2_count: '1 tool',
      cat3_title: 'Productivity',
      cat3_count: '2 tools',
      cat4_title: 'Health & Lifestyle',
      cat4_count: '2 tools',
      tool1_name: 'Calorie Calculator',
      tool1_desc: 'Calculate your BMR, TDEE and daily calorie targets for weight loss, maintenance or muscle gain.',
      tool2_name: 'Color Converter',
      tool2_desc: 'Convert between HEX, RGB, HSL, CMYK formats with live preview and WCAG contrast checker.',
      tool3_name: 'Pomodoro Timer',
      tool3_desc: '25-minute focus sessions with 5-minute breaks. Track your productivity and stay in the zone.',
      tool4_name: 'Unit Converter',
      tool4_desc: 'Convert length, weight, temperature and area units instantly with real-time results.',
      tool5_name: 'Random Picker',
      tool5_desc: 'Draw one from a list, or split a group into teams. Perfect for lucky draws, raffles and random selection.',
      tool6_name: 'Case Converter',
      tool6_desc: 'Convert text to camelCase, PascalCase, snake_case, kebab-case and more instantly.',
      tool7_name: 'JSON Formatter',
      tool7_desc: 'Format, minify, and validate JSON data instantly. Real-time syntax checking and character count.',
      tool8_name: 'Regex Tester',
      tool8_desc: 'Test regular expressions in real-time with match highlighting, groups, and flags support.',
      tool9_name: 'Timestamp Converter',
      tool9_desc: 'Convert between Unix timestamp and human-readable date. Supports seconds, milliseconds, and current time.',
      tool10_name: 'Base64 Encoder',
      tool10_desc: 'Encode and decode Base64 strings instantly. All processing done locally in your browser.',
      tool11_name: 'JWT Decoder',
      tool11_desc: 'Decode and inspect JSON Web Tokens. View header, payload, and claims with expiration status.',
      tool12_name: 'Hash Generator',
      tool12_desc: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes instantly. All computed locally in your browser.',
      open_tool: 'Open tool',
      tag_metric: 'Metric/Imperial',
      tag_contrast: 'Contrast Check',
      features_title: 'All tools include',
      feat_bilingual: 'Bilingual EN / ZH',
      feat_mobile: 'Mobile Friendly',
      feat_fast: 'Instant Results',
      footer: '© 2026 Free Online Tools · No signup required',
      adPlaceholder: 'Advertisement Space'
    },
    zh: {
      site_title: '免费在线工具',
      site_desc: '12款免费工具 · 无需注册 · 工具内无广告 · 首次加载后离线可用',
      cat1_title: '开发者工具',
      cat1_count: '7个工具',
      cat2_title: '设计与颜色',
      cat2_count: '1个工具',
      cat3_title: '效率工具',
      cat3_count: '2个工具',
      cat4_title: '健康生活',
      cat4_count: '2个工具',
      tool1_name: '卡路里计算器',
      tool1_desc: '计算你的基础代谢率(BMR)、每日总消耗(TDEE)和目标热量，支持减脂、维持、增肌三种方案。',
      tool2_name: '颜色转换器',
      tool2_desc: 'HEX、RGB、HSL、CMYK 格式实时互转，支持颜色预览和 WCAG 对比度检查。',
      tool3_name: '番茄钟计时器',
      tool3_desc: '25分钟专注、5分钟休息，自动循环。追踪专注轮次，保持高效节奏。',
      tool4_name: '单位换算器',
      tool4_desc: '长度、重量、温度、面积实时换算，输入即得结果。',
      tool5_name: '随机抽签与分组',
      tool5_desc: '从名单中随机抽取一人或自动分成若干小组，适用于抽签、摇号、随机分组等场景。',
      tool6_name: '驼峰下划线命名转换',
      tool6_desc: '输入文字，实时转换为驼峰、帕斯卡、下划线、短横线等6种编程命名格式。',
      tool7_name: 'JSON 格式化器',
      tool7_desc: '实时格式化、美化、校验 JSON 数据，支持语法检查和字符统计。',
      tool8_name: '正则表达式测试器',
      tool8_desc: '实时测试正则表达式，支持匹配分组高亮和标志位切换。',
      tool9_name: 'Unix 时间戳转换器',
      tool9_desc: '时间戳与可读日期互转，支持秒/毫秒，自动显示当前时间。',
      tool10_name: 'Base64 编解码器',
      tool10_desc: '文本与 Base64 格式实时互转，全部在浏览器本地完成。',
      tool11_name: 'JWT 解码器',
      tool11_desc: '解析 JSON Web Token，查看 Header、Payload 和 Claims 及过期状态。',
      tool12_name: '哈希生成器',
      tool12_desc: '生成 MD5、SHA-1、SHA-256、SHA-512 哈希值，全部在浏览器本地计算。',
      open_tool: '打开工具',
      tag_metric: '公制/英制',
      tag_contrast: '对比度检查',
      features_title: '所有工具均包含',
      feat_bilingual: '中英文双语',
      feat_mobile: '移动端适配',
      feat_fast: '即时计算',
      footer: '© 2026 免费在线工具 · 无需注册',
      adPlaceholder: '广告位'
    }
  };

  let lang = 'en';

  function toggleLang() {
    lang = lang === 'en' ? 'zh' : 'en';
    document.getElementById('langBtn').textContent = lang === 'en' ? '中文' : 'EN';
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.dataset.i18n;
      if (i18n[lang][key]) el.textContent = i18n[lang][key];
    });
  }
